apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: helios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: helios/worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: helios-config
            - secretRef:
                name: helios-secrets
