// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: helios/v1/control_plane.proto

package heliosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_GetHealth_FullMethodName              = "/helios.v1.ControlPlaneService/GetHealth"
	ControlPlaneService_GetReady_FullMethodName               = "/helios.v1.ControlPlaneService/GetReady"
	ControlPlaneService_RegisterWorker_FullMethodName         = "/helios.v1.ControlPlaneService/RegisterWorker"
	ControlPlaneService_HeartbeatWorker_FullMethodName        = "/helios.v1.ControlPlaneService/HeartbeatWorker"
	ControlPlaneService_ListWorkers_FullMethodName            = "/helios.v1.ControlPlaneService/ListWorkers"
	ControlPlaneService_StartTaskExecution_FullMethodName     = "/helios.v1.ControlPlaneService/StartTaskExecution"
	ControlPlaneService_CompleteTaskExecution_FullMethodName  = "/helios.v1.ControlPlaneService/CompleteTaskExecution"
	ControlPlaneService_FailTaskExecution_FullMethodName      = "/helios.v1.ControlPlaneService/FailTaskExecution"
	ControlPlaneService_CreateWorkflow_FullMethodName         = "/helios.v1.ControlPlaneService/CreateWorkflow"
	ControlPlaneService_ListWorkflows_FullMethodName          = "/helios.v1.ControlPlaneService/ListWorkflows"
	ControlPlaneService_GetWorkflow_FullMethodName            = "/helios.v1.ControlPlaneService/GetWorkflow"
	ControlPlaneService_ListWorkflowTasks_FullMethodName      = "/helios.v1.ControlPlaneService/ListWorkflowTasks"
	ControlPlaneService_ListWorkflowEvents_FullMethodName     = "/helios.v1.ControlPlaneService/ListWorkflowEvents"
	ControlPlaneService_GetTask_FullMethodName                = "/helios.v1.ControlPlaneService/GetTask"
	ControlPlaneService_CancelWorkflow_FullMethodName         = "/helios.v1.ControlPlaneService/CancelWorkflow"
	ControlPlaneService_PlannerIntent_FullMethodName          = "/helios.v1.ControlPlaneService/PlannerIntent"
	ControlPlaneService_PlannerDryRun_FullMethodName          = "/helios.v1.ControlPlaneService/PlannerDryRun"
	ControlPlaneService_AnalyzeWorkflowFailure_FullMethodName = "/helios.v1.ControlPlaneService/AnalyzeWorkflowFailure"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
	RegisterWorker(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (*WorkerRegistrationResult, error)
	HeartbeatWorker(ctx context.Context, in *HeartbeatWorkerRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*WorkerListResponse, error)
	StartTaskExecution(ctx context.Context, in *StartTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CompleteTaskExecution(ctx context.Context, in *CompleteTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	FailTaskExecution(ctx context.Context, in *FailTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowSummary, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*WorkflowListResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowSummary, error)
	ListWorkflowTasks(ctx context.Context, in *ListWorkflowTasksRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
	ListWorkflowEvents(ctx context.Context, in *ListWorkflowEventsRequest, opts ...grpc.CallOption) (*WorkflowEventListResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskRecord, error)
	CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error)
	PlannerIntent(ctx context.Context, in *PlannerIntentRequest, opts ...grpc.CallOption) (*PlannerIntentResponse, error)
	PlannerDryRun(ctx context.Context, in *PlannerIntentRequest, opts ...grpc.CallOption) (*PlannerDryRunResponse, error)
	AnalyzeWorkflowFailure(ctx context.Context, in *AnalyzeWorkflowFailureRequest, opts ...grpc.CallOption) (*FailureAnalysisResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetReady(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RegisterWorker(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (*WorkerRegistrationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerRegistrationResult)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) HeartbeatWorker(ctx context.Context, in *HeartbeatWorkerRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_HeartbeatWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*WorkerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerListResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) StartTaskExecution(ctx context.Context, in *StartTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_StartTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CompleteTaskExecution(ctx context.Context, in *CompleteTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CompleteTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) FailTaskExecution(ctx context.Context, in *FailTaskExecutionRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_FailTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowSummary)
	err := c.cc.Invoke(ctx, ControlPlaneService_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*WorkflowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowListResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowSummary)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListWorkflowTasks(ctx context.Context, in *ListWorkflowTasksRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListWorkflowTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListWorkflowEvents(ctx context.Context, in *ListWorkflowEventsRequest, opts ...grpc.CallOption) (*WorkflowEventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowEventListResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListWorkflowEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskRecord)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWorkflowResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CancelWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) PlannerIntent(ctx context.Context, in *PlannerIntentRequest, opts ...grpc.CallOption) (*PlannerIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlannerIntentResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_PlannerIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) PlannerDryRun(ctx context.Context, in *PlannerIntentRequest, opts ...grpc.CallOption) (*PlannerDryRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlannerDryRunResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_PlannerDryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) AnalyzeWorkflowFailure(ctx context.Context, in *AnalyzeWorkflowFailureRequest, opts ...grpc.CallOption) (*FailureAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailureAnalysisResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_AnalyzeWorkflowFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
type ControlPlaneServiceServer interface {
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	GetReady(context.Context, *ReadyRequest) (*ReadyResponse, error)
	RegisterWorker(context.Context, *WorkerRegistration) (*WorkerRegistrationResult, error)
	HeartbeatWorker(context.Context, *HeartbeatWorkerRequest) (*StatusResponse, error)
	ListWorkers(context.Context, *ListWorkersRequest) (*WorkerListResponse, error)
	StartTaskExecution(context.Context, *StartTaskExecutionRequest) (*StatusResponse, error)
	CompleteTaskExecution(context.Context, *CompleteTaskExecutionRequest) (*StatusResponse, error)
	FailTaskExecution(context.Context, *FailTaskExecutionRequest) (*StatusResponse, error)
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*WorkflowSummary, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*WorkflowListResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowSummary, error)
	ListWorkflowTasks(context.Context, *ListWorkflowTasksRequest) (*TaskListResponse, error)
	ListWorkflowEvents(context.Context, *ListWorkflowEventsRequest) (*WorkflowEventListResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*TaskRecord, error)
	CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error)
	PlannerIntent(context.Context, *PlannerIntentRequest) (*PlannerIntentResponse, error)
	PlannerDryRun(context.Context, *PlannerIntentRequest) (*PlannerDryRunResponse, error)
	AnalyzeWorkflowFailure(context.Context, *AnalyzeWorkflowFailureRequest) (*FailureAnalysisResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetReady(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReady not implemented")
}
func (UnimplementedControlPlaneServiceServer) RegisterWorker(context.Context, *WorkerRegistration) (*WorkerRegistrationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedControlPlaneServiceServer) HeartbeatWorker(context.Context, *HeartbeatWorkerRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatWorker not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*WorkerListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedControlPlaneServiceServer) StartTaskExecution(context.Context, *StartTaskExecutionRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTaskExecution not implemented")
}
func (UnimplementedControlPlaneServiceServer) CompleteTaskExecution(context.Context, *CompleteTaskExecutionRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTaskExecution not implemented")
}
func (UnimplementedControlPlaneServiceServer) FailTaskExecution(context.Context, *FailTaskExecutionRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailTaskExecution not implemented")
}
func (UnimplementedControlPlaneServiceServer) CreateWorkflow(context.Context, *CreateWorkflowRequest) (*WorkflowSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*WorkflowListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListWorkflowTasks(context.Context, *ListWorkflowTasksRequest) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowTasks not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListWorkflowEvents(context.Context, *ListWorkflowEventsRequest) (*WorkflowEventListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowEvents not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetTask(context.Context, *GetTaskRequest) (*TaskRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedControlPlaneServiceServer) CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWorkflow not implemented")
}
func (UnimplementedControlPlaneServiceServer) PlannerIntent(context.Context, *PlannerIntentRequest) (*PlannerIntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlannerIntent not implemented")
}
func (UnimplementedControlPlaneServiceServer) PlannerDryRun(context.Context, *PlannerIntentRequest) (*PlannerDryRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlannerDryRun not implemented")
}
func (UnimplementedControlPlaneServiceServer) AnalyzeWorkflowFailure(context.Context, *AnalyzeWorkflowFailureRequest) (*FailureAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeWorkflowFailure not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetReady(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterWorker(ctx, req.(*WorkerRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_HeartbeatWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).HeartbeatWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_HeartbeatWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).HeartbeatWorker(ctx, req.(*HeartbeatWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_StartTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).StartTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_StartTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).StartTaskExecution(ctx, req.(*StartTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CompleteTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CompleteTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CompleteTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CompleteTaskExecution(ctx, req.(*CompleteTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_FailTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).FailTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_FailTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).FailTaskExecution(ctx, req.(*FailTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListWorkflowTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListWorkflowTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListWorkflowTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListWorkflowTasks(ctx, req.(*ListWorkflowTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListWorkflowEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListWorkflowEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListWorkflowEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListWorkflowEvents(ctx, req.(*ListWorkflowEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CancelWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CancelWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CancelWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CancelWorkflow(ctx, req.(*CancelWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_PlannerIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlannerIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).PlannerIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_PlannerIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).PlannerIntent(ctx, req.(*PlannerIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_PlannerDryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlannerIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).PlannerDryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_PlannerDryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).PlannerDryRun(ctx, req.(*PlannerIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_AnalyzeWorkflowFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeWorkflowFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).AnalyzeWorkflowFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_AnalyzeWorkflowFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).AnalyzeWorkflowFailure(ctx, req.(*AnalyzeWorkflowFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helios.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _ControlPlaneService_GetHealth_Handler,
		},
		{
			MethodName: "GetReady",
			Handler:    _ControlPlaneService_GetReady_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _ControlPlaneService_RegisterWorker_Handler,
		},
		{
			MethodName: "HeartbeatWorker",
			Handler:    _ControlPlaneService_HeartbeatWorker_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _ControlPlaneService_ListWorkers_Handler,
		},
		{
			MethodName: "StartTaskExecution",
			Handler:    _ControlPlaneService_StartTaskExecution_Handler,
		},
		{
			MethodName: "CompleteTaskExecution",
			Handler:    _ControlPlaneService_CompleteTaskExecution_Handler,
		},
		{
			MethodName: "FailTaskExecution",
			Handler:    _ControlPlaneService_FailTaskExecution_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _ControlPlaneService_CreateWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _ControlPlaneService_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _ControlPlaneService_GetWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflowTasks",
			Handler:    _ControlPlaneService_ListWorkflowTasks_Handler,
		},
		{
			MethodName: "ListWorkflowEvents",
			Handler:    _ControlPlaneService_ListWorkflowEvents_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ControlPlaneService_GetTask_Handler,
		},
		{
			MethodName: "CancelWorkflow",
			Handler:    _ControlPlaneService_CancelWorkflow_Handler,
		},
		{
			MethodName: "PlannerIntent",
			Handler:    _ControlPlaneService_PlannerIntent_Handler,
		},
		{
			MethodName: "PlannerDryRun",
			Handler:    _ControlPlaneService_PlannerDryRun_Handler,
		},
		{
			MethodName: "AnalyzeWorkflowFailure",
			Handler:    _ControlPlaneService_AnalyzeWorkflowFailure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helios/v1/control_plane.proto",
}
