apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helios-prod-like
  namespace: argocd
  labels:
    app.kubernetes.io/name: helios
    app.kubernetes.io/part-of: helios
    app.kubernetes.io/environment: prod-like
spec:
  project: default
  source:
    repoURL: https://github.com/gaurav-gs7/helios.git
    targetRevision: main
    path: deploy/k8s/overlays/prod-like
  destination:
    server: https://kubernetes.default.svc
    namespace: helios
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
