apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/part-of: helios
      app.kubernetes.io/environment: dev

images:
  - name: ghcr.io/gauravgs7/helios/control-plane
    newName: ghcr.io/gauravgs7/helios/control-plane
    newTag: dev
  - name: ghcr.io/gauravgs7/helios/worker
    newName: ghcr.io/gauravgs7/helios/worker
    newTag: dev
  - name: ghcr.io/gauravgs7/helios/planner
    newName: ghcr.io/gauravgs7/helios/planner
    newTag: dev

patches:
  - path: config-patch.yaml
  - path: secret-patch.yaml
  - path: replica-patch.yaml
